# Generated by Django 6.1 on 2026-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alumnos', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
