# Generated by Django 6.1 on 2026-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alumnos', '0003_curso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
