# Generated by Django 6.1 on 2026-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alumnos', '0004_curso_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
